version: "3"
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    working_dir: "/usr/src/app/src"
    volumes:
      - "./src:/usr/src/app/src"
    ports:
      - 9000:9000
      - 3000:3000