export const SUPERESCALAR_CONFIG = {
    FUNCTIONAL_UNIT_MIN: 1,
    FUNCTIONAL_UNIT_MAX: 10,
    LATENCY_MIN: 0,
    LATENCY_MAX: 100,
    ISSUE_GRADE_MIN: 1,
    ISSUE_GRADE_MAX: 16,
    CACHE_BLOCKS_MIN: 1,
    CACHE_BLOCKS_MAX: 100,
    CACHE_LINES_MIN: 1,
    CACHE_LINES_MAX: 1024,
};

export const VLIW_CONFIG = {
    FUNCTIONAL_UNIT_MIN: 1,
    FUNCTIONAL_UNIT_MAX: 10,
    LATENCY_MIN: 0,
    LATENCY_MAX: 100,
    ISSUE_GRADE_MIN: 1,
    ISSUE_GRADE_MAX: 16
};

export const BATCH_CONFIG = {
    LATENCY_MIN: 0,
    LATENCY_MAX: 100,
    CACHE_FAIL_PERCENTAGE_MIN: 0,
    CACHE_FAIL_PERCENTAGE_MAX: 100
};
