export const MACHINE_REGISTER_SIZE = 64;
export const MEMORY_SIZE = 1024;
 
 export const SUPERESCALAR_CONFIG = {
    FUNCTIONAL_UNIT_MIN: 1,
    FUNCTIONAL_UNIT_MAX: 10,
    LATENCY_MIN: 0,
    LATENCY_MAX: 100,
    ISSUE_GRADE_MIN: 1,
    ISSUE_GRADE_MAX: 16
 }