# .github/workflows/deploy.yml
# This workflow constitutes the CD pipeline of generating production releases.
name: build & deploy
on:
  push:
    tags:
      - '*'
jobs:
  build:
    uses: oxcabe/SIMDE/.github/workflows/build.yml@main
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: ./dist
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
