name: reviewdog

on: [ pull_request ]

jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
            version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.x
      - run: pnpm install --frozen-lockfile
      - uses: mongolyy/reviewdog-action-biome@v1
